// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: party.proto

package net.runelite.client.party;

final class Party {
    private Party() {
    }

    public interface DataOrBuilder extends
            // @@protoc_insertion_point(interface_extends:party.Data)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>string type = 2;</code>
         *
         * @return The type.
         */
        java.lang.String getType();

        /**
         * <code>string type = 2;</code>
         *
         * @return The bytes for type.
         */
        com.google.protobuf.ByteString
        getTypeBytes();

        /**
         * <code>bytes data = 1;</code>
         *
         * @return The data.
         */
        com.google.protobuf.ByteString getData();
    }

    public interface C2SOrBuilder extends
            // @@protoc_insertion_point(interface_extends:party.C2S)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>.party.Join join = 1;</code>
         *
         * @return Whether the join field is set.
         */
        boolean hasJoin();

        /**
         * <code>.party.Join join = 1;</code>
         *
         * @return The join.
         */
        Join getJoin();

        /**
         * <code>.party.Part part = 2;</code>
         *
         * @return Whether the part field is set.
         */
        boolean hasPart();

        /**
         * <code>.party.Part part = 2;</code>
         *
         * @return The part.
         */
        Part getPart();

        /**
         * <code>.party.Data data = 3;</code>
         *
         * @return Whether the data field is set.
         */
        boolean hasData();

        /**
         * <code>.party.Data data = 3;</code>
         *
         * @return The data.
         */
        Data getData();

        C2S.MsgCase getMsgCase();
    }

    /**
     * Protobuf type {@code party.C2S}
     */


    public interface UserJoinOrBuilder extends
            // @@protoc_insertion_point(interface_extends:party.UserJoin)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>int64 partyId = 1;</code>
         *
         * @return The partyId.
         */
        long getPartyId();

        /**
         * <code>int64 memberId = 2;</code>
         *
         * @return The memberId.
         */
        long getMemberId();
    }

    public interface PartyDataOrBuilder extends com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>int64 partyId = 1;</code>
         *
         * @return The partyId.
         */
        long getPartyId();

        /**
         * <code>int64 memberId = 2;</code>
         *
         * @return The memberId.
         */
        long getMemberId();

        /**
         * <code>string type = 4;</code>
         *
         * @return The type.
         */
        java.lang.String getType();

        /**
         * <code>string type = 4;</code>
         *
         * @return The bytes for type.
         */
        com.google.protobuf.ByteString
        getTypeBytes();

        /**
         * <code>bytes data = 3;</code>
         *
         * @return The data.
         */
        com.google.protobuf.ByteString getData();
    }

    public interface S2COrBuilder extends
            // @@protoc_insertion_point(interface_extends:party.S2C)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>.party.UserJoin join = 1;</code>
         *
         * @return Whether the join field is set.
         */
        boolean hasJoin();

        /**
         * <code>.party.UserJoin join = 1;</code>
         *
         * @return The join.
         */
        UserJoin getJoin();

        /**
         * <code>.party.UserPart part = 2;</code>
         *
         * @return Whether the part field is set.
         */
        boolean hasPart();

        /**
         * <code>.party.UserPart part = 2;</code>
         *
         * @return The part.
         */
        UserPart getPart();

        /**
         * <code>.party.PartyData data = 3;</code>
         *
         * @return Whether the data field is set.
         */
        boolean hasData();

        /**
         * <code>.party.PartyData data = 3;</code>
         *
         * @return The data.
         */
        PartyData getData();

        S2C.MsgCase getMsgCase();
    }

}
